// Hardware add-ons: custom bookshelf speakers and subwoofers described in a
// small JSON document ("audiospace-hardware", version 1). The same code
// validates add-ons in the app and in scripts/validate-addon.mjs, so a file
// generated by hand or by an AI assistant can be checked before importing.
//
// A model is a spec sheet (driver size, enclosure, f3, sensitivity, power …)
// that runs through the same physical model as the built-in catalogue. An
// optional measured on-axis frequency response is turned into model-specific
// voicing filters, so the simulation reproduces the real speaker's tonality.
//
// Add-ons are pure data: nothing in them is executed, all text is rendered as
// text, colours must be #rrggbb and ids are reduced to [a-z0-9-].

import { finalizeBookshelf, finalizeSub, slug } from './generator.js';
import { speakerResponseSpecs, subResponseSpecs } from './response.js';
import { cascadeMagnitudeDb } from '../dsp/biquad.js';
import { fitFilters, smoothOctave } from '../dsp/fit.js';
import { octaveGrid, clamp } from '../util/math.js';

export const ADDON_FORMAT = 'audiospace-hardware';
export const ADDON_VERSION = 1;
export const CUSTOM_PREFIX = 'custom-';
/** Bump when the normalisation/fitting changes so stored add-ons are rebuilt. */
export const VALIDATOR_REVISION = 1;

const TWEETER_TYPES = ['dome', 'horn', 'amt', 'ribbon', 'coax', 'none'];
const ENCLOSURES = ['ported', 'sealed', 'pr'];
const PORTS = ['front', 'rear', 'bottom', 'side'];
const PHASES = ['switch', 'variable', 'dsp', 'fixed'];
const FILTER_TYPES = ['peaking', 'lowshelf', 'highshelf'];
const STYLE_KEYS = ['cabinet', 'baffle', 'woofer', 'tweeter', 'accent'];

// ------------------------------------------------------------ field tables
// type: string | number | integer | boolean | enum | object | strings | style | filters | points | id | range

const COMMON = {
  brand: { type: 'string', required: true, max: 60, doc: 'Manufacturer, e.g. "Wharfedale".' },
  model: { type: 'string', required: true, max: 80, doc: 'Model name, e.g. "Diamond 12.1".' },
  id: { type: 'id', doc: 'Optional stable id (a–z, 0–9, -); defaults to brand + model. Always prefixed with "custom-".' },
  price: { type: 'number', min: 0, max: 100000, unit: 'USD', doc: 'Street price (bookshelf: per pair). Used for the price filter.' },
  enclosure: { type: 'enum', values: ENCLOSURES, required: true, doc: 'ported (bass reflex), sealed (acoustic suspension) or pr (passive radiator).' },
  port: { type: 'enum', values: PORTS, doc: 'Port position for ported designs.' },
  qtc: { type: 'number', min: 0.4, max: 1.5, doc: 'Total Q of a sealed alignment (0.5 = overdamped, 0.707 = Butterworth).' },
  portBumpDb: { type: 'number', min: -3, max: 6, unit: 'dB', doc: 'Lift just above f3 from the port/radiator tuning.' },
  maxSpl: { type: 'number', min: 70, max: 140, unit: 'dB SPL', doc: 'Maximum output at 1 m (estimated from power and sensitivity if omitted).' },
  dims: { type: 'object', doc: 'Outer dimensions in cm: { "w": 20, "h": 32, "d": 25 }.', fields: {
    w: { type: 'number', required: true, min: 3, max: 200, unit: 'cm' },
    h: { type: 'number', required: true, min: 3, max: 200, unit: 'cm' },
    d: { type: 'number', required: true, min: 3, max: 200, unit: 'cm' },
    weightKg: { type: 'number', min: 0.1, max: 200, unit: 'kg' },
  } },
  features: { type: 'strings', maxItems: 12, max: 80, doc: 'Short feature tags shown on the model page.' },
  estimated: { type: 'strings', maxItems: 40, max: 40, doc: 'Names of fields that are estimates rather than published figures.' },
  style: { type: 'style', doc: 'Colours for the illustration: { "cabinet": "#2b1d14", "baffle", "woofer", "tweeter", "accent" } as #rrggbb.' },
  voicing: { type: 'filters', doc: 'Explicit tonal balance as up to 16 EQ filters (ignored when "response" is given).' },
  response: { type: 'points', doc: 'Measured on-axis response: [[frequencyHz, dB], …] (at least 8 points spanning ≥ 1 octave).' },
  source: { type: 'string', max: 300, doc: 'Where the figures come from (URL or text).' },
  notes: { type: 'string', max: 2000, doc: 'Free-form notes.' },
};

export const SPEAKER_FIELDS = {
  ...COMMON,
  active: { type: 'boolean', doc: 'true for powered speakers with a built-in amplifier.' },
  ampWatts: { type: 'number', min: 1, max: 2000, unit: 'W', doc: 'Powered speakers: amplifier power per channel (required when active).' },
  rmsWatts: { type: 'number', min: 1, max: 2000, unit: 'W', doc: 'Passive speakers: continuous power handling (required when passive).' },
  peakWatts: { type: 'number', min: 1, max: 10000, unit: 'W' },
  woofer: { type: 'number', required: true, min: 1, max: 15, unit: 'in', doc: 'Woofer diameter in inches.' },
  wooferMaterial: { type: 'string', max: 80 },
  tweeter: { type: 'object', doc: '{ "size": 1, "type": "dome", "material": "Silk" }; type is one of dome, horn, amt, ribbon, coax, none.', fields: {
    size: { type: 'number', min: 0, max: 3, unit: 'in' },
    type: { type: 'enum', values: TWEETER_TYPES },
    material: { type: 'string', max: 80 },
  } },
  ways: { type: 'integer', min: 1, max: 5, doc: 'Number of ways (1 = full-range).' },
  freqLow: { type: 'number', min: 10, max: 500, unit: 'Hz', doc: 'Published lower frequency limit (usually the −6/−10 dB point).' },
  freqHigh: { type: 'number', min: 2000, max: 100000, unit: 'Hz', doc: 'Published upper frequency limit.' },
  f3: { type: 'number', min: 15, max: 300, unit: 'Hz', doc: '−3 dB bass extension (required unless "response" is given).' },
  sensitivity: { type: 'number', min: 70, max: 115, unit: 'dB', doc: 'dB SPL at 2.83 V / 1 m (required for passive speakers).' },
  impedance: { type: 'number', min: 2, max: 32, unit: 'Ω', doc: 'Nominal impedance (required for passive speakers).' },
  crossoverHz: { type: 'number', min: 100, max: 10000, nullable: true, unit: 'Hz', doc: 'Internal crossover frequency.' },
};

export const SUB_FIELDS = {
  ...COMMON,
  driver: { type: 'number', required: true, min: 4, max: 24, unit: 'in', doc: 'Driver diameter in inches.' },
  count: { type: 'integer', min: 1, max: 8, doc: 'Number of active drivers (e.g. 2 for force-cancelling designs).' },
  material: { type: 'string', max: 80, doc: 'Cone material.' },
  rmsWatts: { type: 'number', required: true, min: 10, max: 10000, unit: 'W', doc: 'Continuous amplifier power.' },
  peakWatts: { type: 'number', min: 10, max: 20000, unit: 'W' },
  freqLow: { type: 'number', min: 5, max: 200, unit: 'Hz' },
  freqHigh: { type: 'number', min: 40, max: 500, unit: 'Hz' },
  f3: { type: 'number', min: 5, max: 120, unit: 'Hz', doc: '−3 dB bass extension (required unless "response" is given).' },
  sensitivity: { type: 'number', min: 70, max: 115, unit: 'dB', doc: 'Equivalent 1 W / 1 m efficiency (estimated from the driver if omitted).' },
  phase: { type: 'enum', values: PHASES, doc: 'Phase control: switch, variable, dsp or fixed.' },
  lpfRange: { type: 'range', min: 20, max: 400, unit: 'Hz', doc: 'Built-in low-pass range [low, high].' },
};

export const ADDON_FIELDS = {
  format: { type: 'string', required: true, doc: `Must be "${ADDON_FORMAT}".` },
  version: { type: 'integer', required: true, min: 1, max: 1, doc: 'Format version: 1.' },
  name: { type: 'string', required: true, max: 80, doc: 'Add-on name shown in the app.' },
  id: { type: 'id', doc: 'Optional add-on id; importing an add-on with the same id replaces it.' },
  author: { type: 'string', max: 80 },
  description: { type: 'string', max: 500 },
  url: { type: 'string', max: 300 },
  speakers: { type: 'array', maxItems: 100, doc: 'Bookshelf/stand-mount speakers.' },
  subwoofers: { type: 'array', maxItems: 100, doc: 'Subwoofers.' },
};

// ------------------------------------------------------------ primitives

const isObj = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const show = (v) => {
  try {
    const s = JSON.stringify(v);
    return s && s.length > 40 ? `${s.slice(0, 37)}…` : s;
  } catch {
    return String(v);
  }
};
const unit = (d) => (d.unit ? ` ${d.unit}` : '');

function cleanString(s) {
  // Strip control characters; collapse whitespace.
  return s.replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/\s+/g, ' ').trim();
}

function cleanId(s) {
  return slug(String(s)).slice(0, 60);
}

/**
 * Check `obj` against a field table. Returns the cleaned object with only
 * known fields; records problems in ctx.errors / ctx.warnings.
 */
function checkFields(obj, fields, path, ctx) {
  const out = {};
  for (const key of Object.keys(obj)) {
    if (!(key in fields) && !key.startsWith('$')) ctx.warnings.push({ path: `${path}.${key}`, message: 'unknown field, ignored' });
  }
  for (const [key, d] of Object.entries(fields)) {
    const p = `${path}.${key}`;
    const v = obj[key];
    if (v === undefined || (v === null && !d.nullable)) {
      if (d.required) ctx.errors.push({ path: p, message: `is required${d.doc ? ` — ${d.doc}` : ''}` });
      continue;
    }
    if (v === null) {
      out[key] = null;
      continue;
    }
    const bad = (msg) => ctx.errors.push({ path: p, message: `${msg} (got ${show(v)})` });
    switch (d.type) {
      case 'string':
        if (typeof v !== 'string') bad('must be a string');
        else if (!cleanString(v) && d.required) bad('must not be empty');
        else if (v.length > d.max) bad(`must be at most ${d.max} characters`);
        else out[key] = cleanString(v);
        break;
      case 'id':
        if (typeof v !== 'string' || !cleanId(v)) bad('must be a short id using a–z, 0–9 and -');
        else out[key] = cleanId(v);
        break;
      case 'number':
      case 'integer':
        if (typeof v !== 'number' || !Number.isFinite(v)) bad(`must be a number${typeof v === 'string' ? ', not a string' : ''}`);
        else if (d.type === 'integer' && !Number.isInteger(v)) bad('must be a whole number');
        else if ((d.min != null && v < d.min) || (d.max != null && v > d.max)) bad(`must be between ${d.min} and ${d.max}${unit(d)}`);
        else out[key] = v;
        break;
      case 'boolean':
        if (typeof v !== 'boolean') bad('must be true or false');
        else out[key] = v;
        break;
      case 'enum':
        if (!d.values.includes(v)) bad(`must be one of ${d.values.join(', ')}`);
        else out[key] = v;
        break;
      case 'object':
        if (!isObj(v)) bad('must be an object');
        else out[key] = checkFields(v, d.fields, p, ctx);
        break;
      case 'strings':
        if (!Array.isArray(v) || v.some((x) => typeof x !== 'string')) bad('must be a list of strings');
        else if (v.length > d.maxItems) bad(`must have at most ${d.maxItems} entries`);
        else out[key] = v.map((x) => cleanString(x).slice(0, d.max)).filter(Boolean);
        break;
      case 'range':
        if (!Array.isArray(v) || v.length !== 2 || v.some((x) => typeof x !== 'number' || !Number.isFinite(x))) bad('must be [low, high]');
        else if (v[0] >= v[1] || v[0] < d.min || v[1] > d.max) bad(`must be [low, high] with ${d.min} ≤ low < high ≤ ${d.max}${unit(d)}`);
        else out[key] = [v[0], v[1]];
        break;
      case 'style':
        out[key] = checkStyle(v, p, ctx);
        break;
      case 'filters':
        out[key] = checkFilters(v, p, ctx);
        break;
      case 'points':
        out[key] = checkPoints(v, p, ctx);
        break;
      case 'array':
        if (!Array.isArray(v)) bad('must be a list');
        else if (v.length > d.maxItems) bad(`must have at most ${d.maxItems} entries`);
        else out[key] = v;
        break;
    }
  }
  return out;
}

function checkStyle(v, path, ctx) {
  if (!isObj(v)) {
    ctx.errors.push({ path, message: `must be an object of #rrggbb colours (got ${show(v)})` });
    return undefined;
  }
  const out = {};
  for (const k of Object.keys(v)) {
    if (!STYLE_KEYS.includes(k)) ctx.warnings.push({ path: `${path}.${k}`, message: `unknown colour, ignored (use ${STYLE_KEYS.join(', ')})` });
  }
  for (const k of STYLE_KEYS) {
    if (v[k] === undefined) continue;
    if (typeof v[k] !== 'string' || !/^#[0-9a-fA-F]{6}$/.test(v[k])) ctx.errors.push({ path: `${path}.${k}`, message: `must be a colour like "#1c1c1f" (got ${show(v[k])})` });
    else out[k] = v[k].toLowerCase();
  }
  return out;
}

function checkFilters(v, path, ctx) {
  if (!Array.isArray(v)) {
    ctx.errors.push({ path, message: `must be a list of filters (got ${show(v)})` });
    return undefined;
  }
  if (v.length > 16) {
    ctx.errors.push({ path, message: 'must have at most 16 filters' });
    return undefined;
  }
  const out = [];
  v.forEach((f, i) => {
    const p = `${path}[${i}]`;
    if (!isObj(f)) {
      ctx.errors.push({ path: p, message: `must be { "type", "frequency", "gain", "Q" } (got ${show(f)})` });
      return;
    }
    const c = checkFields(f, {
      type: { type: 'enum', values: FILTER_TYPES, required: true },
      frequency: { type: 'number', required: true, min: 10, max: 30000, unit: 'Hz' },
      gain: { type: 'number', required: true, min: -24, max: 24, unit: 'dB' },
      Q: { type: 'number', min: 0.1, max: 30 },
    }, p, ctx);
    if (c.type && c.frequency != null && c.gain != null) out.push({ type: c.type, frequency: c.frequency, gain: c.gain, Q: c.Q ?? (c.type === 'peaking' ? 1 : 0.707) });
  });
  return out;
}

/** Accepts [[f, dB], …] or [{ "f"|"freq"|"frequency": …, "db"|"dB"|"spl": … }, …]. */
function checkPoints(v, path, ctx) {
  if (!Array.isArray(v)) {
    ctx.errors.push({ path, message: `must be a list of [frequencyHz, dB] pairs (got ${show(v)})` });
    return undefined;
  }
  if (v.length < 8 || v.length > 4000) {
    ctx.errors.push({ path, message: `must have between 8 and 4000 points (got ${v.length})` });
    return undefined;
  }
  const pts = [];
  for (let i = 0; i < v.length; i++) {
    const e = v[i];
    let f;
    let db;
    if (Array.isArray(e) && e.length >= 2) [f, db] = e;
    else if (isObj(e)) {
      f = e.f ?? e.freq ?? e.frequency ?? e.hz;
      db = e.db ?? e.dB ?? e.spl ?? e.level;
    }
    if (typeof f !== 'number' || typeof db !== 'number' || !Number.isFinite(f) || !Number.isFinite(db)) {
      ctx.errors.push({ path: `${path}[${i}]`, message: `must be [frequencyHz, dB] with numbers (got ${show(e)})` });
      return undefined;
    }
    if (f < 5 || f > 50000 || db < -100 || db > 150) {
      ctx.errors.push({ path: `${path}[${i}]`, message: `frequency must be 5–50000 Hz and level −100…150 dB (got ${show(e)})` });
      return undefined;
    }
    pts.push([f, db]);
  }
  let sorted = true;
  for (let i = 1; i < pts.length; i++) if (pts[i][0] <= pts[i - 1][0]) sorted = false;
  if (!sorted) {
    ctx.warnings.push({ path, message: 'points were not in ascending frequency order; sorted (duplicates removed)' });
    pts.sort((a, b) => a[0] - b[0]);
    for (let i = pts.length - 1; i > 0; i--) if (pts[i][0] === pts[i - 1][0]) pts.splice(i, 1);
  }
  if (pts.length < 8 || pts[pts.length - 1][0] / pts[0][0] < 2) {
    ctx.errors.push({ path, message: 'must span at least one octave with 8 or more distinct frequencies' });
    return undefined;
  }
  return pts;
}

// ------------------------------------------------------------ response fitting

/** Level (dB) of a measured curve at f by log-frequency interpolation. */
function interpPoints(pts, f) {
  if (f <= pts[0][0]) return pts[0][1];
  const n = pts.length;
  if (f >= pts[n - 1][0]) return pts[n - 1][1];
  let lo = 0;
  let hi = n - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (pts[mid][0] <= f) lo = mid;
    else hi = mid;
  }
  const t = Math.log(f / pts[lo][0]) / Math.log(pts[hi][0] / pts[lo][0]);
  return pts[lo][1] + (pts[hi][1] - pts[lo][1]) * t;
}

function meanIn(freqs, vals, f1, f2) {
  let s = 0;
  let n = 0;
  for (let i = 0; i < freqs.length; i++) {
    if (freqs[i] >= f1 && freqs[i] <= f2) {
      s += vals[i];
      n++;
    }
  }
  return n ? s / n : NaN;
}

function referenceBand(kind, lo, hi) {
  const [a, b] = kind === 'subwoofer' ? [30, 80] : [300, 3000];
  const f1 = Math.max(a, lo);
  const f2 = Math.min(b, hi);
  // Need at least half an octave of overlap; otherwise use the whole range.
  return f2 / f1 >= Math.SQRT2 ? [f1, f2] : [lo, hi];
}

/** −3 dB point of a measured response relative to its reference band. */
export function estimateF3(kind, pts) {
  const lo = pts[0][0];
  const hi = pts[pts.length - 1][0];
  const grid = octaveGrid(lo, hi, 48);
  const db = smoothOctave(grid, Float64Array.from(grid, (f) => interpPoints(pts, f)), 6);
  const [b1] = referenceBand(kind, lo, hi);
  const ref = meanIn(grid, db, ...referenceBand(kind, lo, hi));
  let i = grid.findIndex((f) => f >= b1);
  for (; i > 0; i--) {
    if (db[i - 1] < ref - 3) {
      const t = (ref - 3 - db[i]) / (db[i - 1] - db[i]);
      return Math.round(Math.exp(Math.log(grid[i]) + t * (Math.log(grid[i - 1]) - Math.log(grid[i]))));
    }
  }
  return null;
}

/**
 * Voicing filters that make the modelled response match a measurement:
 * fit(measured − model), both levelled to the reference band.
 */
export function fitMeasuredVoicing(kind, hwNoVoicing, pts) {
  const specs = kind === 'subwoofer' ? subResponseSpecs(hwNoVoicing) : speakerResponseSpecs(hwNoVoicing);
  const [gMin, gMax] = kind === 'subwoofer' ? [10, 400] : [20, 20000];
  const lo = Math.max(gMin, pts[0][0]);
  const hi = Math.min(gMax, pts[pts.length - 1][0]);
  const grid = octaveGrid(lo, hi, 24);
  const model = cascadeMagnitudeDb(specs, grid);
  const meas = Float64Array.from(grid, (f) => interpPoints(pts, f));
  const band = referenceBand(kind, lo, hi);
  const offset = meanIn(grid, Float64Array.from(grid, (_, i) => meas[i] - model[i]), ...band);
  const diff = Float64Array.from(grid, (_, i) => meas[i] - offset - model[i]);
  const target = smoothOctave(grid, diff, 6);
  const fit = fitFilters(grid, target, { maxFilters: 12, fMin: lo, fMax: hi, maxBoost: 12, maxCut: 18, qMin: 0.4, qMax: 10, tolerance: 0.35 });
  const filters = fit.filters.map((f) => ({ type: f.type, frequency: Math.round(f.frequency * 10) / 10, Q: Math.round((f.Q ?? 0.707) * 100) / 100, gain: Math.round(f.gain * 10) / 10 }));
  // Residual after applying the fitted filters (for the report).
  const withFit = cascadeMagnitudeDb([...specs, ...filters], grid);
  let sq = 0;
  for (let i = 0; i < grid.length; i++) sq += (meas[i] - offset - withFit[i]) ** 2;
  return {
    filters,
    rmsErrorDb: Math.round(Math.sqrt(sq / grid.length) * 100) / 100,
    measured: { freqs: Array.from(grid, (f) => Math.round(f * 100) / 100), db: Array.from(meas, (v) => Math.round((v - offset) * 100) / 100) },
  };
}

// ------------------------------------------------------------ models

function modelId(c) {
  const base = c.id || cleanId(`${c.brand} ${c.model}`);
  return base.startsWith(CUSTOM_PREFIX) ? base : `${CUSTOM_PREFIX}${base}`;
}

function buildSpeaker(c, path, ctx, meta) {
  const warn = (field, message) => ctx.warnings.push({ path: `${path}.${field}`, message });
  const estimated = new Set(c.estimated || []);
  if (!c.active && c.rmsWatts == null) ctx.errors.push({ path: `${path}.rmsWatts`, message: 'is required for passive speakers (set "active": true and "ampWatts" for powered ones)' });
  if (c.active && c.ampWatts == null) ctx.errors.push({ path: `${path}.ampWatts`, message: 'is required for powered speakers ("active": true)' });
  if (!c.active && c.sensitivity == null) ctx.errors.push({ path: `${path}.sensitivity`, message: 'is required for passive speakers (dB SPL at 2.83 V / 1 m)' });
  if (!c.active && c.impedance == null) ctx.errors.push({ path: `${path}.impedance`, message: 'is required for passive speakers (nominal ohms)' });
  if (c.f3 == null && !c.response) ctx.errors.push({ path: `${path}.f3`, message: 'is required unless a measured "response" is given' });
  if (ctx.errors.length) return null;
  const tweeter = { size: c.tweeter?.size ?? (c.tweeter?.type === 'none' ? 0 : 1), type: c.tweeter?.type || 'dome', material: c.tweeter?.material };
  let f3 = c.f3;
  if (f3 == null) {
    f3 = clamp(estimateF3('bookshelf', c.response) ?? c.response[0][0], 15, 300);
    estimated.add('f3');
    warn('f3', `derived from the measured response: ${f3} Hz`);
  }
  if (c.price == null) {
    warn('price', 'not given; assumed $500 (only affects price filters and default port tuning)');
    estimated.add('price');
  }
  if (c.active && c.sensitivity == null) estimated.add('sensitivity');
  const seed = {
    id: modelId(c),
    brand: c.brand,
    model: c.model,
    active: !!c.active,
    ampWatts: c.active ? c.ampWatts : undefined,
    rmsWatts: c.active ? undefined : c.rmsWatts,
    peakWatts: c.peakWatts,
    woofer: c.woofer,
    wooferMaterial: c.wooferMaterial,
    tweeter,
    ways: c.ways ?? (tweeter.type === 'none' ? 1 : 2),
    enclosure: c.enclosure,
    port: c.port,
    freqLow: c.freqLow ?? Math.round(f3 * 0.82),
    freqHigh: c.freqHigh ?? 20000,
    f3,
    qtc: c.qtc,
    portBumpDb: c.portBumpDb,
    sensitivity: c.sensitivity ?? 85,
    impedance: c.impedance ?? 4,
    crossoverHz: c.crossoverHz ?? null,
    maxSpl: c.maxSpl,
    price: c.price ?? 500,
    features: c.features,
    estimated: [...estimated],
    specSource: 'addon',
    addon: meta,
  };
  if (c.dims) seed.dims = dimsOf(c.dims);
  return finishModel('bookshelf', seed, c, path, ctx);
}

function buildSub(c, path, ctx, meta) {
  const warn = (field, message) => ctx.warnings.push({ path: `${path}.${field}`, message });
  const estimated = new Set(c.estimated || []);
  if (c.f3 == null && !c.response) ctx.errors.push({ path: `${path}.f3`, message: 'is required unless a measured "response" is given' });
  if (ctx.errors.length) return null;
  let f3 = c.f3;
  if (f3 == null) {
    f3 = clamp(estimateF3('subwoofer', c.response) ?? c.response[0][0], 5, 120);
    estimated.add('f3');
    warn('f3', `derived from the measured response: ${f3} Hz`);
  }
  if (c.price == null) {
    warn('price', 'not given; assumed $600 (only affects price filters and default port tuning)');
    estimated.add('price');
  }
  if (c.sensitivity == null) estimated.add('sensitivity');
  const seed = {
    id: modelId(c),
    brand: c.brand,
    model: c.model,
    driver: c.driver,
    count: c.count ?? 1,
    material: c.material,
    enclosure: c.enclosure,
    port: c.port,
    rmsWatts: c.rmsWatts,
    peakWatts: c.peakWatts,
    freqLow: c.freqLow ?? Math.round(f3 * 0.88),
    freqHigh: c.freqHigh ?? 160,
    f3,
    qtc: c.qtc,
    portBumpDb: c.portBumpDb,
    sensitivity: c.sensitivity,
    maxSpl: c.maxSpl,
    price: c.price ?? 600,
    phase: c.phase,
    lpfRange: c.lpfRange,
    features: c.features,
    estimated: [...estimated],
    specSource: 'addon',
    addon: meta,
  };
  if (c.dims) seed.dims = dimsOf(c.dims);
  return finishModel('subwoofer', seed, c, path, ctx);
}

function dimsOf(d) {
  const litres = Math.round(((d.w * d.h * d.d) / 1000) * 10) / 10;
  return { w: d.w, h: d.h, d: d.d, litres, weightKg: d.weightKg ?? Math.round(litres * 0.6 * 10) / 10 };
}

function finishModel(kind, seed, c, path, ctx) {
  const finalize = kind === 'subwoofer' ? finalizeSub : finalizeBookshelf;
  if (c.style) seed.style = { ...finalize({ ...seed, style: undefined }, null).style, ...c.style };
  if (c.response) {
    if (c.voicing) ctx.warnings.push({ path: `${path}.voicing`, message: 'ignored because a measured "response" is given' });
    const fit = fitMeasuredVoicing(kind, finalize({ ...seed, voicing: [] }, null), c.response);
    seed.voicing = fit.filters;
    seed.measured = fit.measured;
    seed.fit = { filters: fit.filters.length, rmsErrorDb: fit.rmsErrorDb };
    if (fit.rmsErrorDb > 3) ctx.warnings.push({ path: `${path}.response`, message: `the model matches the measurement to ${fit.rmsErrorDb} dB RMS; check f3/enclosure if this seems high` });
  } else if (c.voicing) {
    seed.voicing = c.voicing;
  }
  const m = finalize(seed, null);
  if (c.source) m.source = c.source;
  if (c.notes) m.notes = c.notes;
  return m;
}

// ------------------------------------------------------------ entry point

/**
 * Validate and normalise an add-on (a parsed JSON value or a JSON string).
 * @returns {{ok: boolean, errors: {path, message}[], warnings: {path, message}[], addon: object|null, models: object[]}}
 */
export function validateAddon(input) {
  const ctx = { errors: [], warnings: [] };
  let doc = input;
  if (typeof input === 'string') {
    try {
      doc = JSON.parse(input);
    } catch (err) {
      return { ok: false, errors: [{ path: '(file)', message: `is not valid JSON: ${err.message}` }], warnings: [], addon: null, models: [] };
    }
  }
  if (!isObj(doc)) return { ok: false, errors: [{ path: '(file)', message: 'must be a JSON object' }], warnings: [], addon: null, models: [] };
  const top = checkFields(doc, ADDON_FIELDS, '$', ctx);
  if (doc.format !== undefined && doc.format !== ADDON_FORMAT) ctx.errors.push({ path: '$.format', message: `must be "${ADDON_FORMAT}" (got ${show(doc.format)})` });
  if (ctx.errors.length) return { ok: false, errors: ctx.errors, warnings: ctx.warnings, addon: null, models: [] };
  const speakers = top.speakers || [];
  const subwoofers = top.subwoofers || [];
  if (!speakers.length && !subwoofers.length) {
    ctx.errors.push({ path: '$', message: 'must contain at least one entry in "speakers" or "subwoofers"' });
    return { ok: false, errors: ctx.errors, warnings: ctx.warnings, addon: null, models: [] };
  }
  const addonId = top.id || cleanId(top.name) || 'addon';
  const meta = { id: addonId, name: top.name, author: top.author || null };
  const models = [];
  const cleaned = { speakers: [], subwoofers: [] };
  const ids = new Map();
  const each = (list, kind) => {
    list.forEach((raw, i) => {
      const path = `$.${kind === 'subwoofer' ? 'subwoofers' : 'speakers'}[${i}]`;
      if (!isObj(raw)) {
        ctx.errors.push({ path, message: `must be an object (got ${show(raw)})` });
        return;
      }
      const local = { errors: [], warnings: ctx.warnings };
      const c = checkFields(raw, kind === 'subwoofer' ? SUB_FIELDS : SPEAKER_FIELDS, path, local);
      let m = null;
      if (!local.errors.length) m = kind === 'subwoofer' ? buildSub(c, path, local, meta) : buildSpeaker(c, path, local, meta);
      ctx.errors.push(...local.errors);
      if (!m) return;
      if (ids.has(m.id)) {
        ctx.errors.push({ path: `${path}.id`, message: `duplicates the id "${m.id}" of ${ids.get(m.id)} — give one of them an explicit "id"` });
        return;
      }
      ids.set(m.id, path);
      models.push(m);
      (kind === 'subwoofer' ? cleaned.subwoofers : cleaned.speakers).push(c);
    });
  };
  each(speakers, 'bookshelf');
  each(subwoofers, 'subwoofer');
  if (ctx.errors.length) return { ok: false, errors: ctx.errors, warnings: ctx.warnings, addon: null, models: [] };
  const addon = {
    format: ADDON_FORMAT,
    version: ADDON_VERSION,
    id: addonId,
    name: top.name,
    ...(top.author ? { author: top.author } : {}),
    ...(top.description ? { description: top.description } : {}),
    ...(top.url ? { url: top.url } : {}),
    ...(cleaned.speakers.length ? { speakers: cleaned.speakers } : {}),
    ...(cleaned.subwoofers.length ? { subwoofers: cleaned.subwoofers } : {}),
  };
  return { ok: true, errors: [], warnings: ctx.warnings, addon, models };
}

/** A small, valid add-on to start from. */
export function addonTemplate() {
  return {
    $schema: 'https://raw.githubusercontent.com/googpleplaystore/Audio-simulator/HEAD/docs/addons/audiospace-hardware.schema.json',
    format: ADDON_FORMAT,
    version: ADDON_VERSION,
    name: 'My speakers',
    author: 'Your name',
    speakers: [
      {
        brand: 'Example',
        model: 'Monitor 5',
        woofer: 5.25,
        tweeter: { size: 1, type: 'dome', material: 'Silk' },
        enclosure: 'ported',
        f3: 55,
        sensitivity: 87,
        impedance: 8,
        rmsWatts: 80,
        crossoverHz: 2500,
        price: 399,
        estimated: ['crossoverHz'],
      },
    ],
    subwoofers: [
      {
        brand: 'Example',
        model: 'Sub 10',
        driver: 10,
        enclosure: 'sealed',
        rmsWatts: 300,
        f3: 27,
        qtc: 0.65,
        price: 549,
      },
    ],
  };
}
