// Bookshelf speaker catalogue data.
//
// SEEDS: hand-entered from manufacturer-published specifications (rounded;
// where a figure is not published — e.g. sensitivity of powered speakers — a
// documented estimate is used and flagged in `estimated`).
//
// ROSTER: further best-selling models. Their detailed specs are *extrapolated*
// by generator.js from driver size, enclosure type, amplification and price
// tier using loudspeaker physics (Hofmann's iron law style trade-offs) plus
// the brand's house voicing. They are flagged specSource: 'extrapolated'.

export const BOOKSHELF_SEEDS = [
  {
    brand: 'Edifier', model: 'R1280DBs', active: true, ampWatts: 21, woofer: 4, wooferMaterial: 'Paper composite',
    tweeter: { size: 0.51, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 55, freqHigh: 20000, f3: 64, sensitivity: 85, impedance: 4, crossoverHz: 2800, price: 150,
    features: ['Bluetooth 5.0', 'Optical & coaxial', 'Subwoofer out', 'Remote'], estimated: ['sensitivity', 'crossoverHz'],
  },
  {
    brand: 'Klipsch', model: 'RP-600M II', active: false, woofer: 6.5, wooferMaterial: 'Cerametallic',
    tweeter: { size: 1, type: 'horn', material: 'Titanium LTS (90×90 Tractrix horn)' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 45, freqHigh: 25000, f3: 45, sensitivity: 94, impedance: 8, rmsWatts: 100, peakWatts: 400, crossoverHz: 1500, price: 699,
    features: ['Tractrix port', 'Magnetic grilles', 'Bi-wire'],
  },
  {
    brand: 'KEF', model: 'LS50 Meta', active: false, woofer: 5.25, wooferMaterial: 'Aluminium (Uni-Q)',
    tweeter: { size: 1, type: 'coax', material: 'Aluminium dome with MAT' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 47, freqHigh: 45000, f3: 79, sensitivity: 85, impedance: 8, rmsWatts: 100, crossoverHz: 2200, price: 1599,
    features: ['Uni-Q 12th gen', 'Metamaterial Absorption Technology'],
  },
  {
    brand: 'Audioengine', model: 'A2+', active: true, ampWatts: 15, woofer: 2.75, wooferMaterial: 'Kevlar',
    tweeter: { size: 0.75, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 65, freqHigh: 22000, f3: 72, sensitivity: 84, impedance: 4, crossoverHz: 3000, price: 269,
    features: ['Bluetooth aptX', 'USB DAC', 'Sub out'], estimated: ['sensitivity', 'crossoverHz'],
  },
  {
    brand: 'Audioengine', model: 'HD6', active: true, ampWatts: 50, woofer: 5.5, wooferMaterial: 'Kevlar',
    tweeter: { size: 1, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 50, freqHigh: 22000, f3: 55, sensitivity: 86, impedance: 4, crossoverHz: 2500, price: 749,
    features: ['Bluetooth aptX', 'Optical', 'Sub out'], estimated: ['sensitivity', 'crossoverHz'],
  },
  {
    brand: 'Sony', model: 'SS-CS5', active: false, woofer: 5.12, wooferMaterial: 'Mica-reinforced cellular',
    tweeter: { size: 1, type: 'dome', material: 'Polyester soft dome + 0.75" super tweeter' }, ways: 3, enclosure: 'ported', port: 'rear',
    freqLow: 53, freqHigh: 50000, f3: 60, sensitivity: 87, impedance: 6, rmsWatts: 50, peakWatts: 100, crossoverHz: 2500, price: 160,
    features: ['3-way', 'Super tweeter'],
  },
  {
    brand: 'Polk Audio', model: 'T15', active: false, woofer: 5.25, wooferMaterial: 'Dynamic Balance polymer',
    tweeter: { size: 0.75, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 60, freqHigh: 24000, f3: 68, sensitivity: 89, impedance: 8, rmsWatts: 100, crossoverHz: 2500, price: 99,
    features: ['Wall-mountable'],
  },
  {
    brand: 'ELAC', model: 'Debut 2.0 B6.2', active: false, woofer: 6.5, wooferMaterial: 'Aramid fibre',
    tweeter: { size: 1, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'front',
    freqLow: 44, freqHigh: 35000, f3: 50, sensitivity: 87, impedance: 6, rmsWatts: 120, crossoverHz: 2200, price: 379,
    features: ['Front port', 'Andrew Jones design'],
  },
  {
    brand: 'Micca', model: 'PB42X', active: true, ampWatts: 20, woofer: 4, wooferMaterial: 'Carbon fibre',
    tweeter: { size: 0.75, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 60, freqHigh: 20000, f3: 72, sensitivity: 85, impedance: 4, crossoverHz: 3000, price: 150,
    features: ['Class D amp', 'Sub out'], estimated: ['sensitivity', 'crossoverHz', 'freqLow'],
  },
  {
    brand: 'Vanatoo', model: 'Transparent Zero', active: true, ampWatts: 24, woofer: 4, wooferMaterial: 'Aluminium',
    tweeter: { size: 1, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'pr', port: 'rear',
    freqLow: 55, freqHigh: 20000, f3: 60, sensitivity: 86, impedance: 4, crossoverHz: 2500, price: 299,
    features: ['Rear passive radiator', 'DSP', 'USB / optical / Bluetooth'], estimated: ['sensitivity', 'crossoverHz'],
  },
  {
    brand: 'Sonos', model: 'Era 100', active: true, ampWatts: 30, woofer: 3.5, wooferMaterial: 'Polymer midwoofer',
    tweeter: { size: 0.75, type: 'dome', material: 'Dual angled tweeters' }, ways: 2, enclosure: 'sealed', port: null,
    freqLow: 50, freqHigh: 20000, f3: 70, sensitivity: 85, impedance: 4, crossoverHz: 3000, price: 498,
    features: ['Wi-Fi / AirPlay 2', 'Trueplay tuning', 'Stereo pair'], estimated: ['ampWatts', 'woofer', 'freqLow', 'sensitivity'],
  },
  {
    brand: 'Q Acoustics', model: '3020i', active: false, woofer: 5, wooferMaterial: 'Aramid',
    tweeter: { size: 0.9, type: 'dome', material: 'Soft dome' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 64, freqHigh: 30000, f3: 68, sensitivity: 88, impedance: 6, rmsWatts: 75, crossoverHz: 2400, price: 299,
    features: ['Point-to-point bracing', 'Rear port'],
  },
  {
    brand: 'Bowers & Wilkins', model: '607 S3', active: false, woofer: 5, wooferMaterial: 'Continuum cone',
    tweeter: { size: 1, type: 'dome', material: 'Titanium dome' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 52, freqHigh: 28000, f3: 60, sensitivity: 84, impedance: 8, rmsWatts: 100, crossoverHz: 3500, price: 799,
    features: ['Flowport', 'Titanium Dome tweeter'],
  },
  {
    brand: 'PreSonus', model: 'Eris E3.5', active: true, ampWatts: 25, woofer: 3.5, wooferMaterial: 'Woven composite',
    tweeter: { size: 1, type: 'dome', material: 'Silk' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 80, freqHigh: 20000, f3: 85, sensitivity: 85, impedance: 4, crossoverHz: 2800, price: 99,
    features: ['Acoustic tuning controls', 'Headphone out'], estimated: ['sensitivity', 'crossoverHz'],
  },
  {
    brand: 'Dali', model: 'Spektor 2', active: false, woofer: 5.25, wooferMaterial: 'Wood fibre',
    tweeter: { size: 1, type: 'dome', material: 'Soft textile dome' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 59, freqHigh: 26000, f3: 64, sensitivity: 84, impedance: 6, rmsWatts: 100, crossoverHz: 2600, price: 299,
    features: ['Wood-fibre cone'],
  },
  {
    brand: 'Monitor Audio', model: 'Bronze 50', active: false, woofer: 5, wooferMaterial: 'C-CAM',
    tweeter: { size: 1, type: 'dome', material: 'C-CAM gold dome' }, ways: 2, enclosure: 'ported', port: 'rear',
    freqLow: 50, freqHigh: 30000, f3: 58, sensitivity: 86, impedance: 8, rmsWatts: 80, crossoverHz: 2800, price: 449,
    features: ['HiVe II port', '6th generation'],
  },
];

// [brand, model, wooferIn, enclosure, ampWattsPerChannel(0 = passive), pricePair, tweeterType, ways, portPos]
export const BOOKSHELF_ROSTER = [
  ['Edifier', 'R1280T', 4, 'ported', 21, 110, 'dome', 2, 'rear'],
  ['Klipsch', 'R-51M', 5.25, 'ported', 0, 299, 'horn', 2, 'rear'],
  ['Polk Audio', 'Monitor XT15', 5.25, 'ported', 0, 149, 'dome', 2, 'rear'],
  ['Edifier', 'R1700BT', 4, 'ported', 33, 170, 'dome', 2, 'front'],
  ['Klipsch', 'R-41M', 4, 'ported', 0, 199, 'horn', 2, 'rear'],
  ['Pioneer', 'SP-BS22-LR', 4, 'ported', 0, 150, 'dome', 2, 'rear'],
  ['ELAC', 'Debut 2.0 B5.2', 5.25, 'ported', 0, 279, 'dome', 2, 'front'],
  ['Edifier', 'R980T', 4, 'ported', 12, 70, 'dome', 2, 'front'],
  ['Micca', 'MB42X', 4, 'ported', 0, 99, 'dome', 2, 'rear'],
  ['Polk Audio', 'Monitor XT20', 6.5, 'ported', 0, 199, 'dome', 2, 'rear'],
  ['Fluance', 'Ai41', 5, 'ported', 45, 249, 'dome', 2, 'rear'],
  ['JBL', '305P MkII', 5, 'ported', 41, 298, 'dome', 2, 'rear'],
  ['Yamaha', 'HS5', 5, 'ported', 35, 398, 'dome', 2, 'rear'],
  ['KRK', 'Rokit 5 G4', 5.25, 'ported', 55, 358, 'dome', 2, 'front'],
  ['Kanto', 'YU4', 4, 'ported', 35, 399, 'dome', 2, 'rear'],
  ['Audioengine', 'A5+', 5, 'ported', 50, 499, 'dome', 2, 'rear'],
  ['Q Acoustics', '3010i', 4, 'ported', 0, 249, 'dome', 2, 'rear'],
  ['KEF', 'Q150', 5.25, 'ported', 0, 499, 'coax', 2, 'rear'],
  ['Edifier', 'R2000DB', 5, 'ported', 60, 330, 'dome', 2, 'front'],
  ['Mackie', 'CR4-X', 4, 'ported', 25, 170, 'dome', 2, 'rear'],
  ['Fluance', 'Ai61', 6.5, 'ported', 60, 399, 'dome', 2, 'rear'],
  ['Klipsch', 'The Fives', 4.5, 'ported', 80, 849, 'horn', 2, 'rear'],
  ['Polk Audio', 'Signature Elite ES15', 5.25, 'ported', 0, 329, 'dome', 2, 'rear'],
  ['Edifier', 'S1000MKII', 5.5, 'ported', 60, 500, 'dome', 2, 'front'],
  ['Dayton Audio', 'B652-AIR', 6.5, 'ported', 0, 80, 'amt', 2, 'rear'],
  ['Klipsch', 'RP-500M II', 5.25, 'ported', 0, 599, 'horn', 2, 'rear'],
  ['KEF', 'Q350', 6.5, 'ported', 0, 649, 'coax', 2, 'rear'],
  ['Mackie', 'CR3-X', 3, 'ported', 25, 120, 'dome', 2, 'rear'],
  ['JBL', 'Stage A130', 5.25, 'ported', 0, 249, 'dome', 2, 'rear'],
  ['PreSonus', 'Eris E4.5', 4.5, 'ported', 25, 199, 'dome', 2, 'front'],
  ['Wharfedale', 'Diamond 12.1', 4, 'ported', 0, 349, 'dome', 2, 'rear'],
  ['Dali', 'Oberon 1', 5.25, 'ported', 0, 449, 'dome', 2, 'rear'],
  ['Bowers & Wilkins', '606 S3', 6.5, 'ported', 0, 999, 'dome', 2, 'rear'],
  ['Q Acoustics', '3030i', 6.5, 'ported', 0, 399, 'dome', 2, 'rear'],
  ['Kanto', 'YU2', 3, 'ported', 25, 229, 'dome', 2, 'rear'],
  ['Audioengine', 'A1', 2.75, 'ported', 15, 199, 'dome', 2, 'rear'],
  ['Sony', 'SS-B1000', 5, 'ported', 0, 90, 'dome', 2, 'rear'],
  ['Yamaha', 'NS-BP182', 5.12, 'ported', 0, 120, 'dome', 2, 'rear'],
  ['Klipsch', 'R-15PM', 5.25, 'ported', 35, 499, 'horn', 2, 'rear'],
  ['Edifier', 'R1855DB', 4, 'ported', 35, 250, 'dome', 2, 'front'],
  ['JBL', '306P MkII', 6.5, 'ported', 56, 398, 'dome', 2, 'rear'],
  ['KRK', 'Rokit 7 G4', 6.5, 'ported', 72, 498, 'dome', 2, 'front'],
  ['Yamaha', 'HS7', 6.5, 'ported', 48, 498, 'dome', 2, 'rear'],
  ['M-Audio', 'BX4', 4.5, 'ported', 25, 150, 'dome', 2, 'rear'],
  ['M-Audio', 'AV42', 4, 'ported', 10, 99, 'dome', 2, 'rear'],
  ['IK Multimedia', 'iLoud Micro Monitor', 3, 'ported', 25, 299, 'dome', 2, 'front'],
  ['Adam Audio', 'T5V', 5, 'ported', 50, 398, 'ribbon', 2, 'front'],
  ['Adam Audio', 'T7V', 7, 'ported', 50, 598, 'ribbon', 2, 'front'],
  ['Monitor Audio', 'Bronze 100', 6, 'ported', 0, 599, 'dome', 2, 'rear'],
  ['Wharfedale', 'Diamond 12.2', 5, 'ported', 0, 499, 'dome', 2, 'rear'],
  ['Dali', 'Spektor 1', 4.5, 'ported', 0, 249, 'dome', 2, 'rear'],
  ['Fluance', 'SX6', 6.5, 'ported', 0, 249, 'dome', 2, 'rear'],
  ['Polk Audio', 'Signature Elite ES20', 6.5, 'ported', 0, 449, 'dome', 2, 'rear'],
  ['Polk Audio', 'Reserve R100', 5.25, 'ported', 0, 599, 'ribbon', 2, 'rear'],
  ['ELAC', 'Debut Reference DBR62', 6.5, 'ported', 0, 499, 'dome', 2, 'front'],
  ['ELAC', 'Uni-Fi 2.0 UB52', 5.25, 'ported', 0, 599, 'coax', 3, 'front'],
  ['KEF', 'LSX II', 4.5, 'ported', 50, 1399, 'coax', 2, 'rear'],
  ['Klipsch', 'The Sevens', 6.5, 'ported', 100, 999, 'horn', 2, 'rear'],
  ['Kanto', 'YU6', 5.25, 'ported', 50, 499, 'dome', 2, 'rear'],
  ['Q Acoustics', 'M20', 5, 'ported', 65, 399, 'dome', 2, 'rear'],
  ['Mackie', 'CR5-X', 5.25, 'ported', 40, 230, 'dome', 2, 'rear'],
  ['JBL', 'Stage A120', 4.5, 'ported', 0, 199, 'dome', 2, 'rear'],
  ['Jamo', 'S 803', 5.25, 'ported', 0, 249, 'dome', 2, 'rear'],
  ['Triangle', 'Borea BR03', 6.5, 'ported', 0, 599, 'dome', 2, 'front'],
  ['Cambridge Audio', 'SX-50', 5.25, 'ported', 0, 229, 'dome', 2, 'rear'],
  ['PSB', 'Alpha P5', 5.25, 'ported', 0, 349, 'dome', 2, 'rear'],
  ['SVS', 'Prime Bookshelf', 6.5, 'ported', 0, 499, 'dome', 2, 'rear'],
  ['Wharfedale', 'Denton 85th Anniversary', 6.5, 'ported', 0, 999, 'dome', 2, 'rear'],
  ['Dali', 'Oberon 3', 7, 'ported', 0, 649, 'dome', 2, 'rear'],
  ['Neumann', 'KH 80 DSP', 4, 'ported', 50, 1098, 'dome', 2, 'rear'],
  ['Genelec', '8010A', 3, 'ported', 25, 798, 'dome', 2, 'front'],
  ['Audioengine', 'HD3', 2.75, 'ported', 25, 399, 'dome', 2, 'rear'],
  ['Kanto', 'TUK', 5.25, 'ported', 65, 799, 'amt', 2, 'rear'],
  ['Bose', '161', 2.5, 'ported', 0, 179, 'none', 1, 'rear'],
  ['Dayton Audio', 'MK442T', 4, 'ported', 0, 90, 'dome', 3, 'rear'],
  ['Micca', 'RB42', 4, 'ported', 25, 199, 'dome', 2, 'rear'],
  ['KRK', 'Rokit 8 G4', 8, 'ported', 100, 658, 'dome', 2, 'front'],
  ['Yamaha', 'HS8', 8, 'ported', 60, 738, 'dome', 2, 'rear'],
  ['PreSonus', 'Eris E5', 5.25, 'ported', 40, 299, 'dome', 2, 'front'],
  ['M-Audio', 'BX5 D3', 5, 'ported', 50, 258, 'dome', 2, 'front'],
  ['ELAC', 'Debut ConneX DCB41', 4, 'ported', 50, 499, 'dome', 2, 'rear'],
  ['KEF', 'Q Concerto Meta', 6.5, 'ported', 0, 1099, 'coax', 2, 'rear'],
  ['Pyle', 'PCB4BK', 4, 'ported', 0, 40, 'dome', 2, 'front'],
  ['Edifier', 'MR4', 4, 'ported', 21, 130, 'dome', 2, 'rear'],
];
